# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-05 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmConfigInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(max_length=100, verbose_name='Directory Name')),
                ('config_name', models.CharField(max_length=100, verbose_name='Config File Name')),
                ('config_content', models.TextField(verbose_name='Config Content')),
                ('config_flag', models.IntegerField(default=0, verbose_name='Flag(0-1)')),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(default='', max_length=100, verbose_name='Directory Name')),
                ('dir_flag', models.IntegerField(default=0, verbose_name='Status(0-1)')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('finishtime', models.DateTimeField(blank=True, null=True, verbose_name='Finish Time')),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(max_length=100, verbose_name='Directory Name')),
                ('filefullpathname', models.CharField(max_length=200, verbose_name='File Full Path And Name')),
                ('filename', models.CharField(max_length=80, verbose_name='File Name')),
                ('fileflag', models.IntegerField(default=0, verbose_name='Status(0-2)')),
                ('filesize', models.BigIntegerField(verbose_name='File Size(byte)')),
                ('configured', models.IntegerField(default=0, verbose_name='Has Config File(0-1)')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('finishtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Finish Time')),
                ('directory_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Server.DirectoryInfo')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResultCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_string', models.TextField(verbose_name='Search String')),
                ('search_content', models.TextField(verbose_name='Search Content')),
                ('config_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_caches', to='Server.AlgorithmConfigInfo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='User Name')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
            ],
        ),
        migrations.AddField(
            model_name='algorithmconfiginfo',
            name='directory_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='Server.DirectoryInfo'),
        ),
    ]
